# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: serverlesspractice009
# "service" is the name of this project. This will also be added to your AWS resource names.
service: bannerService

provider:
  name: aws
  runtime: nodejs22.x
  region: ap-south-1
  environment:
    BUCKET_NAME: banner-images-bucket-smhemel-dev

resources:
  Resources:
    BannerImagesBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: banner-images-bucket-smhemel-dev

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
