# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: serverlesspractice009
# "service" is the name of this project. This will also be added to your AWS resource names.
service: bannerService

provider:
  name: aws
  runtime: nodejs22.x
  region: ap-south-1
  environment:
    BUCKET_NAME: banner-images-bucket-smhemel-dev
    DYNAMODB_TABLE: Banners
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
      Resource:
        - "arn:aws:s3:::banner-images-bucket-smhemel-dev/*"
    - Effect: "Allow"
      Action:
        - "dynamodb:PutItem"
      Resource:
        - "arn:aws:dynamodb:ap-south-1:245362991910:table/Banners"

resources:
  Resources:
    BannerImagesBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: banner-images-bucket-smhemel-dev
    BannersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Banners
        AttributeDefinitions:
          - AttributeName: fileName
            AttributeType: S
        KeySchema:
          - AttributeName: fileName
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

functions:
  uploadBanner:
    handler: handlers/uploadBanner.getUploadUrl
    events:
      - httpApi:
          path: /upload-banner
          method: post
  confirmUpload:
    handler: handlers/confirmUpload.confirmUpload
    events:
      - s3:
          bucket: banner-images-bucket-smhemel-dev
          event: s3:ObjectCreated:Put
          existing: true
