# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: serverlesspractice009
# "service" is the name of this project. This will also be added to your AWS resource names.
service: productService

provider:
  name: aws
  runtime: nodejs22.x
  region: ap-south-1
  httpApi:
    authorizers:
      myCognitoAuth:
        identitySource: $request.header.Authorization
        issuerUrl: https://cognito-idp.ap-south-1.amazonaws.com/ap-south-1_Hy8Kh4yLg
        audience:
          - 40t596ot83gjo66aupnpgrghl6
  environment:
    BUCKET_NAME: products-images-bucket-smhemel-dev
    DYNAMODB_TABLE: Products
    SNS_TOPIC_ARN: arn:aws:sns:ap-south-1:245362991910:ProductCleanupTopic
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:PutItem"
        - "dynamodb:UpdateItem"
        - "dynamodb:Scan"
        - "dynamodb:DeleteItem"
      Resource:
        - "arn:aws:dynamodb:ap-south-1:245362991910:table/Products"
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
      Resource:
        - "arn:aws:s3:::products-images-bucket-smhemel-dev/*"
    - Effect: "Allow"
      Action:
        - "sns:Publish"
      Resource:
        - "arn:aws:sns:ap-south-1:245362991910:ProductCleanupTopic"

resources:
  Resources:
    ProductsImagesBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: products-images-bucket-smhemel-dev
    ProductTable: 
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Products
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    ProductCleanupTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: ProductCleanupTopic
    ProductCleanupSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        TopicArn: arn:aws:sns:ap-south-1:245362991910:ProductCleanupTopic
        Protocol: email
        Endpoint: smhemel.eu@gmail.com

functions:
  getUploadUrl:
    handler: handlers/getUploadUrl.getUploadUrl
    events:
      - httpApi:
          path: /upload-url
          method: post
          authorizer:
            name: myCognitoAuth
  updateProductImage:
    handler: handlers/updateProductImage.updateProductImage
    events:
      - s3:
          bucket: products-images-bucket-smhemel-dev
          event: s3:ObjectCreated:Put
          existing: true
  cleanupProducts:
    handler: handlers/cleanupProducts.cleanupProducts
    events:
      - schedule:
          rate: rate(2 minutes)
