# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: serverlesspractice009
# "service" is the name of this project. This will also be added to your AWS resource names.
service: orderService

provider:
  name: aws
  runtime: nodejs22.x
  region: ap-south-1
  environment:
    DYNAMODB_TABLE: Orders
    SQS_QUEUE_URL: https://sqs.ap-south-1.amazonaws.com/245362991910/OrderQueue
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:PutItem"
        - "sqs:SendMessage"
        - 'sqs:ReceiveMessage'
        - 'sqs:DeleteMessage'
      Resource:
        - Fn::GetAtt: [OrderTable, Arn]
        - Fn::GetAtt: [OrdersQueue, Arn]

resources:
  Resources:
    OrderTable: 
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Orders
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    OrdersQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: OrderQueue

functions:
  placeOrder:
    handler: handlers/placeOrder.placeOrder
    events:
      - httpApi:
          path: /place-order
          method: post
  processOrder:
    handler: handlers/processOrder.processOrder
    events:
      - sqs:
          arn:
            Fn::GetAtt: [OrdersQueue, Arn]
