# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: serverlesspractice009
# "service" is the name of this project. This will also be added to your AWS resource names.
service: categoryService

provider:
  name: aws
  runtime: nodejs22.x
  region: ap-south-1
  environment:
    BUCKET_NAME: category-images-bucket-smhemel-dev
    DYNAMODB_TABLE: Categories
    SNS_TOPIC_ARN: arn:aws:sns:ap-south-1:245362991910:CategoryCleanupTopic
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
      Resource:
        - "arn:aws:s3:::category-images-bucket-smhemel-dev/*"
    - Effect: "Allow"
      Action:
        - "dynamodb:PutItem"
        - "dynamodb:UpdateItem"
        - "dynamodb:Scan"
        - "dynamodb:DeleteItem"
      Resource:
        - "arn:aws:dynamodb:ap-south-1:245362991910:table/Categories"
    - Effect: "Allow"
      Action:
        - "sns:Publish"
      Resource:
        - "arn:aws:sns:ap-south-1:245362991910:CategoryCleanupTopic"

resources:
  Resources:
    CategoryImagesBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: category-images-bucket-smhemel-dev
    CategoryTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Categories
        AttributeDefinitions:
          - AttributeName: fileName
            AttributeType: S
        KeySchema:
          - AttributeName: fileName
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    CategoryCleanupTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: CategoryCleanupTopic
    CategoryCleanupSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        TopicArn: arn:aws:sns:ap-south-1:245362991910:CategoryCleanupTopic
        Protocol: email
        Endpoint: smhemel.eu@gmail.com

functions:
  getUploadUrl:
    handler: handlers/getUploadUrl.getUploadUrl
    events:
      - httpApi:
          path: /upload-url
          method: post
  getAllCategories:
    handler: handlers/getAllCategories.getAllCategories
    events:
      - httpApi:
          path: /all-categories
          method: get
  updateCategoryImage:
    handler: handlers/updateCategoryImage.updateCategoryImage
    events:
      - s3:
          bucket: category-images-bucket-smhemel-dev
          event: s3:ObjectCreated:Put
          existing: true
  cleanupCategories:
    handler: handlers/cleanupCategories.cleanupCategories
    events:
      -  schedule: rate(2 minutes)
