# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: serverlesspractice009
# "service" is the name of this project. This will also be added to your AWS resource names.
service: authService

provider:
  name: aws
  runtime: nodejs22.x
  region: ap-south-1
  environment:
    CLIENT_ID: ${ssm:/CLIENT_ID}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:PutItem
      Resource:
        - arn:aws:dynamodb:ap-south-1:245362991910:table/Users

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Users # name of the table where users will be stored
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S # S = String
        KeySchema:
          - AttributeName: userId
            KeyType: HASH # HASH = Partition Key
        BillingMode: PAY_PER_REQUEST # Automatically scales read/write capacity based on demand

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
  signUp:
    handler: handlers/signUp.signUp
    events:
      - httpApi:
          path: /signup
          method: post
  confirmSignUp:
    handler: handlers/confirmSignUp.confirmSignUp
    events:
      - httpApi:
          path: /confirm-signup
          method: post
  signIn:
    handler: handlers/signIn.signIn
    events:
      - httpApi:
          path: /signin
          method: post
  signOut:
    handler: handlers/signOut.signOut
    events:
      - httpApi:
          path: /signout
          method: post
